[Scraper]
username = "lorossi" # GitHub Username
token = "" # GitHub Personal Access Token
out_path = "out/" # Folder containing the reports
relevant_topics = ["released"] # Topics to inlcude for the repos in homepage
skip_interactive_names = ["lorenzoros.si-website"] # Repo names to skip
skip_interactive_topics = [
  "library",
  "c-library",
  "javascript-library",
] # Topics to skip for the interactive repos list in homepage


[Renderer]
templates_path = "templates/" # local path for templates folder

[Deployer]
hostname = "lorenzoros.si"     # website url
username = ""                  # ssh username
password = ""                  # ssh key password
key_filename = "id_rsa.key"    # ssh key path
local_path = "../public_html/" # local folder to deploy
remote_path = ""               # remote path
